# Generated by Django 5.1.1 on 2024-10-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
